# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='network.proto',
  package='ffnn',
  syntax='proto3',
  serialized_pb=_b('\n\rnetwork.proto\x12\x04\x66\x66nn\"0\n\x06Weight\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0c\n\x04grid\x18\x03 \x03(\x01\"\x16\n\x04\x42ias\x12\x0e\n\x06vector\x18\x01 \x03(\x01\"\xdc\x01\n\x07Network\x12\x12\n\nlayerSizes\x18\x01 \x03(\x05\x12\x31\n\x0b\x61\x63tivations\x18\x02 \x03(\x0e\x32\x1c.ffnn.Network.ActivationType\x12\x1d\n\x07weights\x18\x03 \x03(\x0b\x32\x0c.ffnn.Weight\x12\x1a\n\x06\x62iases\x18\x04 \x03(\x0b\x32\n.ffnn.Bias\"O\n\x0e\x41\x63tivationType\x12\x0b\n\x07SIGMOID\x10\x00\x12\n\n\x06LINEAR\x10\x01\x12\x08\n\x04RELU\x10\x02\x12\r\n\tTHRESHOLD\x10\x03\x12\x0b\n\x07SOFTMAX\x10\x04\x42\x30\n\x10\x63om.votebin.ffnnB\rNetworkProtos\xaa\x02\x0cVotebin.FFNNb\x06proto3')
)



_NETWORK_ACTIVATIONTYPE = _descriptor.EnumDescriptor(
  name='ActivationType',
  full_name='ffnn.Network.ActivationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINEAR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THRESHOLD', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTMAX', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=239,
  serialized_end=318,
)
_sym_db.RegisterEnumDescriptor(_NETWORK_ACTIVATIONTYPE)


_WEIGHT = _descriptor.Descriptor(
  name='Weight',
  full_name='ffnn.Weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col', full_name='ffnn.Weight.col', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='ffnn.Weight.row', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid', full_name='ffnn.Weight.grid', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=71,
)


_BIAS = _descriptor.Descriptor(
  name='Bias',
  full_name='ffnn.Bias',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='ffnn.Bias.vector', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=95,
)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='ffnn.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layerSizes', full_name='ffnn.Network.layerSizes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activations', full_name='ffnn.Network.activations', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='ffnn.Network.weights', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='biases', full_name='ffnn.Network.biases', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORK_ACTIVATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=318,
)

_NETWORK.fields_by_name['activations'].enum_type = _NETWORK_ACTIVATIONTYPE
_NETWORK.fields_by_name['weights'].message_type = _WEIGHT
_NETWORK.fields_by_name['biases'].message_type = _BIAS
_NETWORK_ACTIVATIONTYPE.containing_type = _NETWORK
DESCRIPTOR.message_types_by_name['Weight'] = _WEIGHT
DESCRIPTOR.message_types_by_name['Bias'] = _BIAS
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Weight = _reflection.GeneratedProtocolMessageType('Weight', (_message.Message,), dict(
  DESCRIPTOR = _WEIGHT,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:ffnn.Weight)
  ))
_sym_db.RegisterMessage(Weight)

Bias = _reflection.GeneratedProtocolMessageType('Bias', (_message.Message,), dict(
  DESCRIPTOR = _BIAS,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:ffnn.Bias)
  ))
_sym_db.RegisterMessage(Bias)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), dict(
  DESCRIPTOR = _NETWORK,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:ffnn.Network)
  ))
_sym_db.RegisterMessage(Network)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020com.votebin.ffnnB\rNetworkProtos\252\002\014Votebin.FFNN'))
# @@protoc_insertion_point(module_scope)
