/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: network.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "network.pb-c.h"
void   ffnn__weight__init
                     (Ffnn__Weight         *message)
{
  static const Ffnn__Weight init_value = FFNN__WEIGHT__INIT;
  *message = init_value;
}
size_t ffnn__weight__get_packed_size
                     (const Ffnn__Weight *message)
{
  assert(message->base.descriptor == &ffnn__weight__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ffnn__weight__pack
                     (const Ffnn__Weight *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ffnn__weight__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ffnn__weight__pack_to_buffer
                     (const Ffnn__Weight *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ffnn__weight__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ffnn__Weight *
       ffnn__weight__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ffnn__Weight *)
     protobuf_c_message_unpack (&ffnn__weight__descriptor,
                                allocator, len, data);
}
void   ffnn__weight__free_unpacked
                     (Ffnn__Weight *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ffnn__weight__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ffnn__bias__init
                     (Ffnn__Bias         *message)
{
  static const Ffnn__Bias init_value = FFNN__BIAS__INIT;
  *message = init_value;
}
size_t ffnn__bias__get_packed_size
                     (const Ffnn__Bias *message)
{
  assert(message->base.descriptor == &ffnn__bias__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ffnn__bias__pack
                     (const Ffnn__Bias *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ffnn__bias__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ffnn__bias__pack_to_buffer
                     (const Ffnn__Bias *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ffnn__bias__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ffnn__Bias *
       ffnn__bias__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ffnn__Bias *)
     protobuf_c_message_unpack (&ffnn__bias__descriptor,
                                allocator, len, data);
}
void   ffnn__bias__free_unpacked
                     (Ffnn__Bias *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ffnn__bias__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ffnn__network__init
                     (Ffnn__Network         *message)
{
  static const Ffnn__Network init_value = FFNN__NETWORK__INIT;
  *message = init_value;
}
size_t ffnn__network__get_packed_size
                     (const Ffnn__Network *message)
{
  assert(message->base.descriptor == &ffnn__network__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ffnn__network__pack
                     (const Ffnn__Network *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ffnn__network__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ffnn__network__pack_to_buffer
                     (const Ffnn__Network *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ffnn__network__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ffnn__Network *
       ffnn__network__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ffnn__Network *)
     protobuf_c_message_unpack (&ffnn__network__descriptor,
                                allocator, len, data);
}
void   ffnn__network__free_unpacked
                     (Ffnn__Network *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ffnn__network__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ffnn__weight__field_descriptors[3] =
{
  {
    "col",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ffnn__Weight, col),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "row",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ffnn__Weight, row),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grid",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Ffnn__Weight, n_grid),
    offsetof(Ffnn__Weight, grid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ffnn__weight__field_indices_by_name[] = {
  0,   /* field[0] = col */
  2,   /* field[2] = grid */
  1,   /* field[1] = row */
};
static const ProtobufCIntRange ffnn__weight__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ffnn__weight__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ffnn.Weight",
  "Weight",
  "Ffnn__Weight",
  "ffnn",
  sizeof(Ffnn__Weight),
  3,
  ffnn__weight__field_descriptors,
  ffnn__weight__field_indices_by_name,
  1,  ffnn__weight__number_ranges,
  (ProtobufCMessageInit) ffnn__weight__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ffnn__bias__field_descriptors[1] =
{
  {
    "vector",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Ffnn__Bias, n_vector),
    offsetof(Ffnn__Bias, vector),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ffnn__bias__field_indices_by_name[] = {
  0,   /* field[0] = vector */
};
static const ProtobufCIntRange ffnn__bias__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ffnn__bias__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ffnn.Bias",
  "Bias",
  "Ffnn__Bias",
  "ffnn",
  sizeof(Ffnn__Bias),
  1,
  ffnn__bias__field_descriptors,
  ffnn__bias__field_indices_by_name,
  1,  ffnn__bias__number_ranges,
  (ProtobufCMessageInit) ffnn__bias__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ffnn__network__activation_type__enum_values_by_number[5] =
{
  { "SIGMOID", "FFNN__NETWORK__ACTIVATION_TYPE__SIGMOID", 0 },
  { "LINEAR", "FFNN__NETWORK__ACTIVATION_TYPE__LINEAR", 1 },
  { "RELU", "FFNN__NETWORK__ACTIVATION_TYPE__RELU", 2 },
  { "THRESHOLD", "FFNN__NETWORK__ACTIVATION_TYPE__THRESHOLD", 3 },
  { "SOFTMAX", "FFNN__NETWORK__ACTIVATION_TYPE__SOFTMAX", 4 },
};
static const ProtobufCIntRange ffnn__network__activation_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex ffnn__network__activation_type__enum_values_by_name[5] =
{
  { "LINEAR", 1 },
  { "RELU", 2 },
  { "SIGMOID", 0 },
  { "SOFTMAX", 4 },
  { "THRESHOLD", 3 },
};
const ProtobufCEnumDescriptor ffnn__network__activation_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ffnn.Network.ActivationType",
  "ActivationType",
  "Ffnn__Network__ActivationType",
  "ffnn",
  5,
  ffnn__network__activation_type__enum_values_by_number,
  5,
  ffnn__network__activation_type__enum_values_by_name,
  1,
  ffnn__network__activation_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ffnn__network__field_descriptors[4] =
{
  {
    "layerSizes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ffnn__Network, n_layersizes),
    offsetof(Ffnn__Network, layersizes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ffnn__Network, n_activations),
    offsetof(Ffnn__Network, activations),
    &ffnn__network__activation_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weights",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ffnn__Network, n_weights),
    offsetof(Ffnn__Network, weights),
    &ffnn__weight__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "biases",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ffnn__Network, n_biases),
    offsetof(Ffnn__Network, biases),
    &ffnn__bias__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ffnn__network__field_indices_by_name[] = {
  1,   /* field[1] = activations */
  3,   /* field[3] = biases */
  0,   /* field[0] = layerSizes */
  2,   /* field[2] = weights */
};
static const ProtobufCIntRange ffnn__network__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ffnn__network__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ffnn.Network",
  "Network",
  "Ffnn__Network",
  "ffnn",
  sizeof(Ffnn__Network),
  4,
  ffnn__network__field_descriptors,
  ffnn__network__field_indices_by_name,
  1,  ffnn__network__number_ranges,
  (ProtobufCMessageInit) ffnn__network__init,
  NULL,NULL,NULL    /* reserved[123] */
};
